version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php72:
    container_name: app72
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_XDEBUG: ${PHP72_XDEBUG}
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php56:
    container_name: app56
    build:
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
        PHP_XDEBUG: ${PHP56_XDEBUG}
        PHP_SWOOLE: ${PHP56_SWOOLE}
        PHP_REDIS: ${PHP56_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_PATH}:/var/log/projects/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql_master:
    container_name: mysql_master
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_MASTER_CONF_FILE1}:/etc/mysql/conf.d/master.cnf:ro
    #   - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    # restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mysql_slave_bak:
    container_name: mysql_salve_bak
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT_SLAVE1}:3306"
    volumes:
      - ${MYSQL_SLAVE_CONF_FILE1}:/etc/mysql/conf.d/slave.cnf:ro
    #   - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    # restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  mysql_slave_data:
    container_name: mysql_slave_data
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT_SLAVE2}:3306"
    volumes:
      - ${MYSQL_SLAVE_CONF_FILE2}:/etc/mysql/conf.d/slave.cnf:ro
    #   - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    # restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    networks:
      - default
    ports:
      - "${REDIS_HOST_PORT}:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  default:
